name: CD - Docker Deploy to Azure

on:
  push:
    branches: [production]
  workflow_dispatch:

jobs:
  docker-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da imagem
        run: docker build -t klztt/fcg-api:latest .

      - name: Push para Docker Hub
        run: docker push klztt/fcg-api:latest

      - name: Login no Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Restart no container do Azure App Service
        run: |
          az webapp restart --name fcg-api-fase2-klztt \
            --resource-group sql-fiap-project
