name: CD - Docker Deploy to Azure

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no Azure com Service Principal
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          auth-type: 'client-secret'

      - name: Deploy do container para Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fcg-api-fase2-klztt'
          images: 'klztt/fcg-api:latest'
