name: CD - Docker Build, Push and Azure Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Login no Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build da imagem Docker
      run: docker build -t klztt/fcg-api:latest .

    - name: Push para o Docker Hub
      run: docker push klztt/fcg-api:latest

    - name: Deploy no Azure App Service
      uses: Azure/webapps-deploy@v2
      with:
        app-name: fcg-api-fase2-klztt
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
