name: CI - Build and Test

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Restaurar dependências
      run: dotnet restore FCG.Api/FCG.Api.csproj

    - name: Compilar o projeto
      run: dotnet build FCG.Api/FCG.Api.csproj --configuration Release --no-restore

    - name: Rodar testes
      run: dotnet test FCG.Tests/FCG.Tests.csproj --no-build --verbosity normal
