name: CI - Build, Test and Docker

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]
  workflow_dispatch:

jobs:
  build-test-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restaurar dependências
        run: dotnet restore FCG.Api/FCG.Api.csproj

      - name: Build do projeto
        run: dotnet build FCG.Api/FCG.Api.csproj --configuration Release

      - name: Executar testes
        run: dotnet test FCG.Tests/FCG.Tests.csproj --no-build --verbosity normal

      # Docker
      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da imagem Docker
        run: docker build -t klztt/fcg-api:${{ github.sha }} .

      - name: Push da imagem Docker
        run: docker push klztt/fcg-api:${{ github.sha }}
