name: Build and deploy ASP.Net Core app to Azure Web App - fcg-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restaurar dependências
        run: dotnet restore FCG.Api/FCG.Api.csproj

      - name: Build do projeto
        run: dotnet build FCG.Api/FCG.Api.csproj --configuration Release

      - name: Publicar projeto
        run: dotnet publish FCG.Api/FCG.Api.csproj -c Release -o ./publish

      - name: Upload de artefato para o job de deploy
        uses: actions/upload-artifact@v4
        with:
          name: fcg-api-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Baixar artefato do build
        uses: actions/download-artifact@v4
        with:
          name: fcg-api-app

      - name: Login no Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_135A767DD9C84BA7B9B79ABEEE5EFBD0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B41C41B90D414827A1094EA7F5CFFBE3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_770738F015004C96AA9AE32CF8EC34CE }}

      - name: Deploy para Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fcg-api'
          slot-name: 'Production'
          package: .
